### ISSUE TITLE
Not able to download designer files

### ISSUE THREAD

**Issue by eric-stanley** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel-livewire#10]
# Prerequisites
Purchase of [Soft UI Dashboard PRO Laravel Livewire](https://www.creative-tim.com/product/soft-ui-dashboard-pro-laravel-livewire)

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
When I click on download designer files, I expect the designer files to be downloaded

# Current Behavior
URL redirects back to downloads page

# Failure Information (for bugs)

## Steps to Reproduce

1. Purchase [Soft UI Dashboard PRO Laravel Livewire](https://www.creative-tim.com/product/soft-ui-dashboard-pro-laravel-livewire)
2. Click on designer files download

## Context

* Device: Desktop
* Operating System: Ubuntu
* Browser and Version: Brave v1.42.88

**Comment by teamupdivision** [comment]
Hello, please check this button link:
![image](https://user-images.githubusercontent.com/45566836/185081379-6e1f01f9-fded-4ec2-af9e-ea1204991f29.png)

**Comment by teamupdivision** [comment]
Please check this button link:
![image](https://user-images.githubusercontent.com/45566836/185081732-db5b3669-7ba1-40d9-93ae-0ceee48cbceb.png)
