### ISSUE TITLE
soft-ui-dashboard-pro.ccs problem with alert-primary class

### ISSUE THREAD

**Issue by seferrara** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel-livewire#6]
The alert-primary class is not working correctly. The alert-warning class, is being repeated.
Attached screenshots
![captured1](https://user-images.githubusercontent.com/19521697/173607993-35c50075-c91c-4249-b2b3-08a41edcd765.png)
![captured2](https://user-images.githubusercontent.com/19521697/173608011-b0c7b204-fea7-48d9-b484-110fce69594b.png)
.

**Comment by groovemen** [comment]
Hello @seferrara,

Thank you for your interest in working with our products, please give us more details about the issue that you encountered - how we can reproduce it?

All the best,
Stefan

**Comment by groovemen** [comment]
Hello @seferrara,

Thank you for using our products, can you please give us more details about this issue? We have checked the product [documentation](https://soft-ui-dashboard-pro-laravel-livewire.creative-tim.com/documentation/bootstrap/alerts/soft-ui-dashboard/index.html) and the alert components are working good.

All the best,
Stefan

**Comment by seferrara** [comment]
Hell

[11:21] Gonzalo Yslas
Hi Marie, we were able to detect that the classes are different in the .css
pro and .css basic files. o Stefan

[image: image.png]

**Comment by teamupdivision** [comment]
Hello, 

Thank you for using Creative TIM products. 

Has the issue been resolved or is there something else we can help you with? 

Thank you.
