### ISSUE TITLE
Missing country flags

### ISSUE THREAD

**Issue by iclicksee** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel-livewire#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Country flags missing, only 5 in the assets folder.

# Current Behavior

Missing flags

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Look in the folder

## Context

Self explanatory

* Device: Mac
* Operating System: Mac
* Browser and Version: All

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hello @iclicksee,

Those are all the flags that are used in the project. Feel free to add extra ones, if you think you need them.

Please let us know if we can help you with anything else.

Best,
UPDIVISION Team
