### ISSUE TITLE
Spatie Permissions implementation

### ISSUE THREAD

**Issue by iclicksee** [creativetimofficial/ct-soft-ui-dashboard-pro-laravel-livewire#9]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

Spatie permissions hasRole to return current user role.

What is the current behavior?
Spatie permissions have been added incorrectly, hasRole functions and other functions aren't working.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

auth()->user()->hasRole([ENTER THE ROLE YOU ARE CHECKING]);
Should return true if you have that role.
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi @iclicksee,

Thank you for your message and for using Creative Tim products. 

We haven’t used in the project Spatie permissions, we used Eloquent Relationships you can find in the Models folder.

Please let us know if there is any other info we can help with.

All the best,
UPDIVISION Team
